name: Kotlin CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Build shadowJar
        run: |
          chmod +x ./gradlew
          ./gradlew frontend:processResources
          ./gradlew -Pprod=true frontend:webpack-bundle || :
          ./gradlew -Pprod=true frontend:webpack-bundle || :
          mkdir backend/build/assets -p
          cp frontend/resources/web/index.html backend/build/assets
          cp frontend/build/bundle backend/build/assets -r
          ./gradlew backend:shadowJar
      - name: Upload artifacts
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'ap-southeast-1'
          SOURCE_DIR: 'backend/build/libs'
      - name: Redeploy
        run: |
          curl https://webhooks.chatbox2.ml/hooks/hwboard2-dev
